# Generated by Django 4.1 on 2022-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_page', '0005_alter_notes_task_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
