# Generated by Django 4.1 on 2022-11-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_page', '0007_alter_notes_descriptions_alter_notes_important_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='datecompleted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
